### ISSUE TITLE
Là một học sinh, tôi muốn có chức năng comment để đưa ra nhận xét, bình luận về trang web. <Vũ Thị Thanh Mai>

### ISSUE THREAD

**Issue by maivtt** [OneThousandDong/INT2208-8-2019#27]
### **Đánh giá INVEST:**

- **Independent** : Dữ liệu từ database được tiến hành độc lập, không sử dụng chung không gian dữ liệu với các user stories khác.

- **Negotiable** : User story này không quá chi tiết nên người dùng có thể linh hoạt trong quá trình thực hiện để phù hợp hơn với các công việc khác trong project.

- **Valuable** : User Story có giá trị với khác hàng, khách hàng được hỗ trợ một cách nhanh chóng nhất.

- **Estimatable** : User story có thể chia nhỏ thành các tasks, dễ dàng hơn trong việc quản lý và thực hiện.

- **Small** : Tính năng đủ nhỏ để xây dựng trong một thời gian ngắn.

- **Testable** : Có thể dễ dàng kiểm thử một cách trực quan và dễ dàng.

### **Task list:**

- [x] Làm rõ yêu cầu (giao diện, database, ...)
https://docs.google.com/document/d/1a4i_31R8WBUAnF91syr1FwBpKoAiTY6rEJt1xWjb74M/edit#heading=h.fvjpas4blmex

- [x] Tìm hiểu designer patterns: Mô hình thiết kế MVC
https://docs.google.com/document/d/1a4i_31R8WBUAnF91syr1FwBpKoAiTY6rEJt1xWjb74M/edit#heading=h.kehlqoeo6d9r

- [x] Tìm hiểu về MySQL để quản lý dữ liệu
https://www.tutorialspoint.com/mysql/

- [x] Tìm hiểu về html, css, bootstrap để làm giao diện comment
https://www.tutorialspoint.com/bootstrap/bootstrap_forms.htm

- [x] Tạo form giao diện
+ Form comment
+ Giao diện hiển thị list comment

- [x] Xử lý, insert dữ liệu người dùng nhập từ form vào database, hiển thị dữ liệu từ database ra màn hình  https://github.com/quangnguyen99/INT2208-8-2019/commit/2b8eb1181bee05539319c807f0b7d4c0ab01b0c0 

- [x] Kiểm thử (black box testing) 
https://docs.google.com/document/d/1a4i_31R8WBUAnF91syr1FwBpKoAiTY6rEJt1xWjb74M/edit#heading=h.zhrswbsdiifd
